name: New Joke
on:
  schedule:
    - cron: "10 * * * *"
jobs:
  Update-Joke:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Updating Joke
        run: |
          chmod +x ./changeJoke.sh
          ./changeJoke.sh
        shell: bash
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add README.md
          git commit -m "Joke updated"
          git push origin main
      - run: echo "This job's status is ${{ job.status }}."
